### ISSUE TITLE
Bluetooth don't work on PS4 Pro CUH 7016b

### ISSUE THREAD

**Issue by Tikilou** [Ps3itaTeam/ps4linux-video-drivers#4]
Hi, bluetooth don't work on CUH 7016b (Pro) 

`[ps4@ps4 ~]$ dmesg|grep Bluetooth
[    0.275032] Bluetooth: Core ver 2.22
[    0.283003] Bluetooth: HCI device and connection manager initialized
[    0.289005] Bluetooth: HCI socket layer initialized
[    0.294005] Bluetooth: L2CAP socket layer initialized
[    0.300011] Bluetooth: SCO socket layer initialized
[    1.739145] Bluetooth: Generic Bluetooth SDIO driver ver 0.1
[    1.788416] Bluetooth: RFCOMM TTY layer initialized
[    1.788424] Bluetooth: RFCOMM socket layer initialized
[    1.788434] Bluetooth: RFCOMM ver 1.11
[    1.875398] Bluetooth: vendor=0x2df, device=0x912e, class=255, fn=2
[    7.157233] Bluetooth: module_cfg_cmd(f1) failed``

**Comment by mirh** [comment]
These are the video drivers. 
Though I guess like there's nobody else on github with issues enabled, so...

Pro has a marvell 88W8897 chip ([also](https://forum.manjaro.org/t/surface-pro-3-wifi-no-networks-detected/31784) used on the surface 3 pro, albeit they may be wired with different protocols). CONFIG_MWIFIEX is the driver responsible for the wifi part. 
While BT_MRVL should be the one for bluetooth, and they are both enabled in .config.

I'm not sure if the problems couldn't be due to missing BT_HCIUART_MRVL, or perhaps if it couldn't be some wrong firmware (e.g. perhaps you need the [ps4 specific one](https://www.psdevwiki.com/ps4/Software_Wireless_BT))
